---
- hosts: localhost
  gather_facts: false

  tasks:
  - name: Register a new value
    shell: echo "/etc/resolv.conf"
    register: PLAY1VAR

  - debug: msg="{{ PLAY1VAR.stdout }}"
  
  - name: Echo the output PLAY1 variable vaule
    shell: cat "{{PLAY1VAR.stdout}}" |tail -1 
    register: PLAY2_RESULTS

  - debug: msg="{{ PLAY2_RESULTS.stdout }}"

